import PDFKit
import MessageUI
import SwiftUI

private enum PreventiveVersionSection: Int, CaseIterable, Identifiable {
    case general
    case checklist
    case steps
    case evidence
    case participants

    var id: Int { rawValue }

    var title: String {
        switch self {
        case .general: "Datos generales"
        case .checklist: "Checklist"
        case .steps: "Pasos del mantenimiento"
        case .evidence: "Evidencias"
        case .participants: "Participantes y firmas"
        }
    }

    var systemImage: String {
        switch self {
        case .general: "doc.text.fill"
        case .checklist: "checklist.checked"
        case .steps: "list.number"
        case .evidence: "photo.on.rectangle.angled"
        case .participants: "person.2.fill"
        }
    }
}

private enum CorrectiveVersionSection: Int, CaseIterable, Identifiable {
    case event
    case failure
    case analysis
    case activities
    case validation
    case conclusions
    case evidence
    case participants

    var id: Int { rawValue }

    var title: String {
        switch self {
        case .event: "Datos del evento"
        case .failure: "Descripción de falla"
        case .analysis: "Análisis de falla"
        case .activities: "Actividades realizadas"
        case .validation: "Pruebas y validación"
        case .conclusions: "Conclusiones y comentarios"
        case .evidence: "Evidencias"
        case .participants: "Participantes y firmas"
        }
    }

    var systemImage: String {
        switch self {
        case .event: "doc.text.fill"
        case .failure: "exclamationmark.bubble.fill"
        case .analysis: "waveform.path.ecg"
        case .activities: "wrench.and.screwdriver.fill"
        case .validation: "checkmark.seal.fill"
        case .conclusions: "text.bubble.fill"
        case .evidence: "photo.on.rectangle.angled"
        case .participants: "person.2.fill"
        }
    }
}

/// Read-only version view. The PDF is generated by the backend and opened locally with PDFKit.
struct PDFPreviewView: View {
    @EnvironmentObject private var session: SessionStore
    let versionID: String

    @State private var detail: APIReportVersionDetail?
    @State private var pdfData: Data?
    @State private var pdfURL: URL?
    @State private var isLoading = true
    @State private var isGenerating = false
    @State private var isPreparingEmail = false
    @State private var isPresentingPDF = false
    @State private var mailDraft: ReportEmailDraft?
    @State private var errorMessage: String?
    @State private var selectedPreventiveSection = PreventiveVersionSection.general
    @State private var selectedCorrectiveSection = CorrectiveVersionSection.event

    private var reportService: ReportAPIService {
        ReportAPIService(
            baseURLString: UserDefaults.standard.string(forKey: "apiBaseURL") ?? ""
        )
    }

    var body: some View {
        ScrollView {
            LazyVStack(
                alignment: .leading,
                spacing: AppSpacing.md,
                pinnedViews: [.sectionHeaders]
            ) {
                if let detail {
                    if detail.reportKind == "PREVENTIVE" {
                        preventiveVersionTitleBar(detail)
                        preventiveVersionHeader(detail)
                        Section {
                            selectedPreventiveContent(detail)
                        } header: {
                            preventiveSectionSelector
                                .padding(.vertical, 4)
                                .background(.ultraThinMaterial)
                        }
                    } else if detail.reportKind == "CORRECTIVE" {
                        correctiveVersionTitleBar(detail)
                        correctiveVersionHeader(detail)
                        Section {
                            selectedCorrectiveContent(detail)
                        } header: {
                            correctiveSectionSelector
                                .padding(.vertical, 4)
                                .background(.ultraThinMaterial)
                        }
                    } else {
                        header(detail)
                        generalData(detail)
                        participants(detail)
                        evidence(detail)
                        calibrationContent(detail)
                        if detail.documentStatus == "FINALIZED" {
                            pdfActions(detail)
                        }
                    }
                } else if isLoading {
                    ProgressView("Cargando versión del reporte")
                        .frame(maxWidth: .infinity, minHeight: 260)
                }

                if let errorMessage {
                    Text(errorMessage)
                        .foregroundStyle(.red)
                        .frame(maxWidth: .infinity, alignment: .leading)
                }
            }
            .padding(AppSpacing.lg)
            .frame(maxWidth: 1_420, alignment: .leading)
            .frame(maxWidth: .infinity)
        }
        .background(MaintenanceScreenBackground())
        .navigationTitle("Versión del reporte")
        .task { await loadDetail() }
        .sheet(isPresented: $isPresentingPDF) {
            if let pdfData {
                PDFDocumentViewer(data: pdfData)
            }
        }
        .sheet(item: $mailDraft) { draft in
            ReportMailComposer(draft: draft) { result in
                switch result {
                case .success(.sent):
                    errorMessage = "Correo preparado y enviado desde Mail."
                case .success:
                    break
                case .failure(let error):
                    errorMessage = error.localizedDescription
                }
            }
        }
    }

    private func correctiveVersionTitleBar(_ detail: APIReportVersionDetail) -> some View {
        ViewThatFits(in: .horizontal) {
            HStack(spacing: AppSpacing.lg) {
                Text("Versión del reporte correctivo")
                    .font(.title3.weight(.bold))
                    .fixedSize(horizontal: true, vertical: false)
                Spacer(minLength: AppSpacing.xl)
                if detail.documentStatus == "FINALIZED" {
                    preventiveVersionActions(detail)
                }
            }
            .frame(maxWidth: .infinity)

            VStack(alignment: .leading, spacing: AppSpacing.sm) {
                Text("Versión del reporte correctivo").font(.title3.weight(.bold))
                if detail.documentStatus == "FINALIZED" {
                    preventiveVersionActions(detail)
                        .frame(maxWidth: .infinity, alignment: .trailing)
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
        .padding(.vertical, AppSpacing.xs)
    }

    private func correctiveVersionHeader(_ detail: APIReportVersionDetail) -> some View {
        VStack(alignment: .leading, spacing: AppSpacing.sm) {
            Text(detail.activity.title)
                .font(.system(.largeTitle, design: .rounded).weight(.black))
            HStack(spacing: AppSpacing.sm) {
                Text("Versión \(detail.versionNumber)")
                    .font(.subheadline.weight(.semibold))
                Text(detail.documentStatus)
                    .font(.caption.weight(.bold))
                    .foregroundStyle(BrandColor.green)
                Text(detail.activity.subsystem).foregroundStyle(.secondary)
            }
            if let summary = detail.summary, !summary.isEmpty {
                Text(summary).foregroundStyle(.secondary)
            }
            Text("Lectura histórica: estos datos pertenecen a esta versión y no se editan desde aquí.")
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .padding(.bottom, AppSpacing.xs)
    }

    private var correctiveSectionSelector: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 0) {
                ForEach(Array(CorrectiveVersionSection.allCases.enumerated()), id: \.element.id) {
                    index, section in
                    Button {
                        withAnimation(.snappy) { selectedCorrectiveSection = section }
                    } label: {
                        HStack(spacing: AppSpacing.sm) {
                            Image(systemName: section.systemImage)
                            Text(String(index + 1))
                                .font(.caption.monospacedDigit())
                                .foregroundStyle(.secondary)
                            Text(section.title)
                                .font(.subheadline.weight(.semibold))
                                .lineLimit(1)
                        }
                        .foregroundStyle(selectedCorrectiveSection == section ? BrandColor.red : .primary)
                        .frame(minWidth: 185, minHeight: 48)
                        .padding(.horizontal, AppSpacing.sm)
                        .background(
                            selectedCorrectiveSection == section ? BrandColor.red.opacity(0.08) : Color.clear,
                            in: RoundedRectangle(cornerRadius: 8)
                        )
                        .overlay {
                            if selectedCorrectiveSection == section {
                                RoundedRectangle(cornerRadius: 8)
                                    .stroke(BrandColor.red.opacity(0.45), lineWidth: 1)
                            }
                        }
                    }
                    .buttonStyle(.plain)
                    .accessibilityLabel("Sección \(index + 1), \(section.title)")

                    if section != CorrectiveVersionSection.allCases.last {
                        Divider().frame(height: 26)
                    }
                }
            }
            .padding(4)
        }
        .background(.thinMaterial, in: RoundedRectangle(cornerRadius: 10))
        .overlay {
            RoundedRectangle(cornerRadius: 10)
                .stroke(BrandColor.glassStroke, lineWidth: 1)
        }
        .sensoryFeedback(.selection, trigger: selectedCorrectiveSection)
    }

    @ViewBuilder
    private func selectedCorrectiveContent(_ detail: APIReportVersionDetail) -> some View {
        if let report = detail.correctiveReport {
            switch selectedCorrectiveSection {
            case .event:
                correctiveEvent(detail, report: report)
            case .failure:
                correctiveFailure(report)
            case .analysis:
                correctiveAnalysis(report)
            case .activities:
                correctiveActivities(report)
            case .validation:
                correctiveValidation(report)
            case .conclusions:
                correctiveConclusion(report)
            case .evidence:
                evidence(detail)
            case .participants:
                participants(detail)
            }
        }
    }

    private func preventiveVersionTitleBar(_ detail: APIReportVersionDetail) -> some View {
        ViewThatFits(in: .horizontal) {
            HStack(spacing: AppSpacing.lg) {
                Text("Versión del reporte preventivo")
                    .font(.title3.weight(.bold))
                    .fixedSize(horizontal: true, vertical: false)
                Spacer(minLength: AppSpacing.xl)
                if detail.documentStatus == "FINALIZED" {
                    preventiveVersionActions(detail)
                }
            }
            .frame(maxWidth: .infinity)

            VStack(alignment: .leading, spacing: AppSpacing.sm) {
                Text("Versión del reporte preventivo")
                    .font(.title3.weight(.bold))
                if detail.documentStatus == "FINALIZED" {
                    preventiveVersionActions(detail)
                        .frame(maxWidth: .infinity, alignment: .trailing)
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
        .padding(.vertical, AppSpacing.xs)
    }

    private func preventiveVersionHeader(_ detail: APIReportVersionDetail) -> some View {
        VStack(alignment: .leading, spacing: AppSpacing.sm) {
            Text(detail.activity.title)
                .font(.system(.largeTitle, design: .rounded).weight(.black))
            HStack(spacing: AppSpacing.sm) {
                Text("Versión \(detail.versionNumber)")
                    .font(.subheadline.weight(.semibold))
                Text(detail.documentStatus)
                    .font(.caption.weight(.bold))
                    .foregroundStyle(BrandColor.green)
                Text(detail.activity.subsystem)
                    .foregroundStyle(.secondary)
            }
            if let summary = detail.summary, !summary.isEmpty {
                Text(summary).foregroundStyle(.secondary)
            }
            Text("Lectura histórica: estos datos pertenecen a esta versión y no se editan desde aquí.")
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .padding(.bottom, AppSpacing.xs)
    }

    private func preventiveVersionActions(_ detail: APIReportVersionDetail) -> some View {
        HStack(spacing: AppSpacing.sm) {
            if detail.generatedReport != nil {
                Button("Abrir PDF", systemImage: "doc.viewfinder") {
                    Task { await loadPDF() }
                }
                .buttonStyle(.glassProminent)
            } else {
                Button(isGenerating ? "Generando..." : "Generar PDF", systemImage: "doc.badge.plus") {
                    Task { await generatePDF() }
                }
                .buttonStyle(.glassProminent)
                .disabled(isGenerating)
            }

            if detail.generatedReport != nil {
                Button {
                    Task { await prepareEmail(for: detail) }
                } label: {
                    if isPreparingEmail {
                        ProgressView()
                    } else {
                        Label("Enviar por correo", systemImage: "envelope.fill")
                    }
                }
                .buttonStyle(.glass)
                .disabled(isGenerating || isPreparingEmail)
            }
        }
        .fixedSize(horizontal: true, vertical: false)
    }

    private var preventiveSectionSelector: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 0) {
                ForEach(Array(PreventiveVersionSection.allCases.enumerated()), id: \.element.id) {
                    index, section in
                    Button {
                        withAnimation(.snappy) {
                            selectedPreventiveSection = section
                        }
                    } label: {
                        HStack(spacing: AppSpacing.sm) {
                            Image(systemName: section.systemImage)
                                .font(.headline)
                            Text(String(index + 1))
                                .font(.caption.monospacedDigit())
                                .foregroundStyle(.secondary)
                            Text(section.title)
                                .font(.subheadline.weight(.semibold))
                                .lineLimit(1)
                        }
                        .foregroundStyle(
                            selectedPreventiveSection == section ? BrandColor.red : .primary
                        )
                        .frame(minWidth: 185, minHeight: 48)
                        .padding(.horizontal, AppSpacing.sm)
                        .background(
                            selectedPreventiveSection == section
                                ? BrandColor.red.opacity(0.08)
                                : Color.clear,
                            in: RoundedRectangle(cornerRadius: 8)
                        )
                        .overlay {
                            if selectedPreventiveSection == section {
                                RoundedRectangle(cornerRadius: 8)
                                    .stroke(BrandColor.red.opacity(0.45), lineWidth: 1)
                            }
                        }
                    }
                    .buttonStyle(.plain)
                    .accessibilityLabel("Sección \(index + 1), \(section.title)")

                    if section != PreventiveVersionSection.allCases.last {
                        Divider().frame(height: 26)
                    }
                }
            }
            .padding(4)
        }
        .background(.thinMaterial, in: RoundedRectangle(cornerRadius: 10))
        .overlay {
            RoundedRectangle(cornerRadius: 10)
                .stroke(BrandColor.glassStroke, lineWidth: 1)
        }
        .sensoryFeedback(.selection, trigger: selectedPreventiveSection)
    }

    @ViewBuilder
    private func selectedPreventiveContent(_ detail: APIReportVersionDetail) -> some View {
        switch selectedPreventiveSection {
        case .general:
            generalData(detail)
        case .checklist:
            reportChecklists(detail)
        case .steps:
            steps(detail)
        case .evidence:
            preventiveEvidence(detail)
        case .participants:
            participants(detail)
        }
    }

    @ViewBuilder
    private func preventiveEvidence(_ detail: APIReportVersionDetail) -> some View {
        if detail.evidence.isEmpty {
            GlassPanel {
                VStack(alignment: .leading, spacing: AppSpacing.md) {
                    SectionHeaderText(title: "Evidencias", subtitle: "Fotografías asociadas al reporte")
                    Text("No hay evidencias guardadas en esta versión.")
                        .foregroundStyle(.secondary)
                }
            }
        } else {
            evidence(detail)
        }
    }

    private func header(_ detail: APIReportVersionDetail) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                Text(detail.activity.internalCode)
                    .font(.caption.weight(.bold))
                    .foregroundStyle(BrandColor.red)
                Text(detail.activity.title)
                    .font(.system(.largeTitle, design: .rounded).weight(.black))
                HStack(spacing: AppSpacing.sm) {
                    Text("Versión \(detail.versionNumber)")
                    Text(detail.documentStatus)
                        .font(.caption.weight(.bold))
                        .foregroundStyle(BrandColor.green)
                }
                if let summary = detail.summary, !summary.isEmpty {
                    Text(summary)
                        .foregroundStyle(.secondary)
                }
                Text("Lectura histórica: estos datos pertenecen a esta versión y no se editan desde aquí.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
    }

    private func generalData(_ detail: APIReportVersionDetail) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(title: "Datos generales", subtitle: "Información guardada en el reporte")
                LazyVGrid(
                    columns: [GridItem(.adaptive(minimum: 260), spacing: AppSpacing.md)],
                    alignment: .leading,
                    spacing: AppSpacing.md
                ) {
                    DetailTile(title: "Sede", value: detail.activity.site.orFallback("No registrada"))
                    DetailTile(title: "Proyecto", value: detail.activity.project.orFallback("No registrado"))
                    DetailTile(title: "Etapa", value: detail.activity.stage.orFallback("No registrada"))
                    DetailTile(title: "Sistema", value: detail.activity.system.orFallback("No registrado"))
                    DetailTile(title: "Subsistema", value: detail.activity.subsystem)
                    DetailTile(title: "Equipos", value: detail.activity.assets.map(\.name).joined(separator: ", ").orFallback("No registrados"))
                    DetailTile(title: "Ubicación física", value: detail.activity.locationPath.orFallback("No registrada"))
                    if let report = detail.preventiveReport {
                        DetailTile(
                            title: "Orden SAP",
                            value: detail.activity.sapOrder.orFallback("No registrada")
                        )
                        DetailTile(
                            title: "Fecha de actividad",
                            value: PeruvianDateFormat.display(report.actualDate)
                        )
                        DetailTile(title: "Inicio de actividad", value: Self.dateTimeFormatter.string(from: report.activityStartedAt))
                        if let endedAt = report.activityEndedAt {
                            DetailTile(title: "Fin de actividad", value: Self.dateTimeFormatter.string(from: endedAt))
                        }
                        DetailTile(title: "Estado final del equipo", value: report.finalResult.orFallback("No registrado"))
                        DetailTile(title: "Comentarios adicionales", value: report.additionalComments.orFallback("Sin comentarios"))
                    }
                }
            }
        }
    }

    @ViewBuilder
    private func reportChecklists(_ detail: APIReportVersionDetail) -> some View {
        let manualItems = detail.manualChecklist ?? []
        let operationalItems = detail.operationalChecklist ?? []

        LazyVGrid(
            columns: [GridItem(.adaptive(minimum: 460), spacing: AppSpacing.md)],
            alignment: .leading,
            spacing: AppSpacing.md
        ) {
            GlassPanel {
                VStack(alignment: .leading, spacing: AppSpacing.md) {
                    SectionHeaderText(
                        title: "Checklist según manual",
                        subtitle: "Referencia documental guardada con esta versión"
                    )
                    if manualItems.isEmpty {
                        Text("Pendiente de agregar")
                            .foregroundStyle(.secondary)
                    } else {
                        ForEach(manualItems.sorted { $0.sequence < $1.sequence }) { item in
                            checklistSnapshotRow(item, showExecution: false)
                        }
                    }
                }
            }
            GlassPanel {
                VStack(alignment: .leading, spacing: AppSpacing.md) {
                    SectionHeaderText(
                        title: "Checklist operativo",
                        subtitle: "Elementos registrados durante esta ejecución"
                    )
                    if operationalItems.isEmpty {
                        Text("Pendiente de agregar")
                            .foregroundStyle(.secondary)
                    } else {
                        ForEach(operationalItems.sorted { $0.sequence < $1.sequence }) { item in
                            checklistSnapshotRow(item, showExecution: true)
                        }
                    }
                }
            }
        }
    }

    private func checklistSnapshotRow(
        _ item: APIReportChecklistItem,
        showExecution: Bool
    ) -> some View {
        VStack(alignment: .leading, spacing: AppSpacing.sm) {
            HStack(spacing: AppSpacing.md) {
                Image(
                    systemName: showExecution
                        ? (item.isChecked == true ? "checkmark.circle.fill" : "circle")
                        : "book.closed.fill"
                )
                .foregroundStyle(
                    showExecution && item.isChecked != true
                        ? Color.secondary
                        : BrandColor.red
                )
                VStack(alignment: .leading, spacing: 3) {
                    Text(item.name)
                        .font(.subheadline.weight(.semibold))
                    if let notes = item.notes, !notes.isEmpty {
                        Text(notes)
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
                Spacer()
                Text(checklistSnapshotQuantity(item, showExecution: showExecution))
                    .font(.caption.monospacedDigit())
                    .foregroundStyle(.secondary)
            }
            ForEach(item.selectedTools ?? []) { tool in
                Label(
                    "\(tool.name) · Serie \(tool.serialNumber)",
                    systemImage: "barcode.viewfinder"
                )
                .font(.caption)
                .foregroundStyle(.secondary)
                .padding(.leading, 34)
            }
        }
        .padding(AppSpacing.sm)
        .background(
            .background.opacity(0.62),
            in: RoundedRectangle(cornerRadius: 10)
        )
    }

    private func checklistSnapshotQuantity(
        _ item: APIReportChecklistItem,
        showExecution: Bool
    ) -> String {
        let quantity = showExecution && item.isChecked == true
            ? item.actualQuantity
            : item.recommendedQuantity
        guard let quantity else {
            return showExecution && item.isChecked != true ? "No llevado" : "Por definir"
        }
        return "\(quantity.formatted(.number.precision(.fractionLength(0...2)))) \(item.unit ?? "unidad")"
    }

    @ViewBuilder
    private func correctiveContent(_ detail: APIReportVersionDetail) -> some View {
        if let report = detail.correctiveReport {
            correctiveFailure(report)
            correctiveActivities(report)
            correctiveValidation(report)
            correctiveConclusion(report)
        }
    }

    @ViewBuilder
    private func calibrationContent(
        _ detail: APIReportVersionDetail
    ) -> some View {
        if let report = detail.calibrationReport {
            GlassPanel {
                VStack(alignment: .leading, spacing: AppSpacing.md) {
                    SectionHeaderText(
                        title: "Calibración del circuito de vía",
                        subtitle: "Mediciones guardadas en esta versión"
                    )
                    DetailTile(
                        title: "Circuito de vía",
                        value: report.trackCircuitName
                    )
                    DetailTile(
                        title: "Ubicación",
                        value: report.location
                    )
                    DetailTile(
                        title: "Fecha de calibración",
                        value: report.calibrationDate
                    )
                    DetailTile(
                        title: "Frecuencia",
                        value: "\(report.frequency.orFallback("-")) Hz"
                    )
                    DetailTile(
                        title: "Jumpers del transmisor",
                        value: report.transmitterJumpers.orFallback("-")
                    )

                    ForEach(report.receivers) { receiver in
                        VStack(alignment: .leading, spacing: AppSpacing.sm) {
                            Label(
                                "Receptor \(receiver.sequence)",
                                systemImage: "dot.radiowaves.left.and.right"
                            )
                            .font(.headline)
                            .foregroundStyle(BrandColor.red)
                            DetailTile(
                                title: "Jumpers",
                                value: receiver.jumpers.orFallback("-")
                            )
                            DetailTile(
                                title: "TCA9",
                                value: receiver.tca9.orFallback("-")
                            )
                            DetailTile(
                                title: "Corriente de riel",
                                value: "\(receiver.railCurrent.orFallback("-")) mA"
                            )
                        }
                        .padding(AppSpacing.md)
                        .background(
                            .background.opacity(0.72),
                            in: RoundedRectangle(cornerRadius: 12)
                        )
                    }
                }
            }
        }
    }

    private func correctiveEvent(
        _ detail: APIReportVersionDetail,
        report: APICorrectiveReport
    ) -> some View {
        ViewThatFits(in: .horizontal) {
            HStack(alignment: .top, spacing: AppSpacing.md) {
                generalData(detail)
                    .frame(minWidth: 680, maxWidth: .infinity, alignment: .topLeading)
                    .layoutPriority(3)
                correctiveEventData(report)
                    .frame(minWidth: 380, maxWidth: 520, alignment: .topLeading)
                    .layoutPriority(2)
            }
            .frame(maxWidth: .infinity, alignment: .topLeading)

            VStack(alignment: .leading, spacing: AppSpacing.md) {
                generalData(detail)
                correctiveEventData(report)
            }
            .frame(maxWidth: .infinity, alignment: .topLeading)
        }
    }

    private func correctiveEventData(_ report: APICorrectiveReport) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(
                    title: "Datos del evento",
                    subtitle: "Información del aviso guardada en esta versión"
                )
                MaintenanceFieldGrid {
                    DetailTile(title: "Evento", value: report.eventCode.orFallback("No registrado"))
                    DetailTile(title: "Nombre del evento SAP", value: report.sapEventName.orFallback("No registrado"))
                    DetailTile(title: "Notificación SAP", value: report.sapNotification.orFallback("No registrada"))
                    DetailTile(title: "Equipo afectado", value: report.affectedAssetPath.orFallback("No registrado"))
                }
            }
        }
    }

    private func correctiveFailure(_ report: APICorrectiveReport) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(
                    title: "Descripción de falla",
                    subtitle: "Información guardada en esta versión"
                )
                DetailTile(
                    title: "Síntoma registrado",
                    value: report.symptom.orFallback("No registrado")
                )
                DetailTile(
                    title: "Descripción técnica",
                    value: report.technicalDescription.orFallback("No registrada")
                )
                DetailTile(
                    title: "Impacto operacional",
                    value: report.operationalImpact.orFallback("No registrado")
                )
            }
        }
    }

    private func correctiveAnalysis(_ report: APICorrectiveReport) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(title: "Análisis de falla")
                DetailTile(
                    title: "Tipo de falla",
                    value: report.failureAnalysisType.orFallback("No registrado")
                )
            }
        }
    }

    private func correctiveActivities(_ report: APICorrectiveReport) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(
                    title: "Actividades realizadas",
                    subtitle: "Intervenciones y cambios de componentes"
                )
                if report.activities.isEmpty {
                    Text("No hay actividades registradas.").foregroundStyle(.secondary)
                } else {
                    ForEach(report.activities) { activity in
                        VStack(alignment: .leading, spacing: AppSpacing.sm) {
                            Label(
                                activity.name,
                                systemImage: activity.replacement == nil
                                    ? "wrench.and.screwdriver"
                                    : "arrow.triangle.2.circlepath"
                            )
                            .font(.headline)

                            if !activity.description.isEmpty {
                                Text(activity.description)
                            }

                            HStack {
                                Text(
                                    "Inicio: \(Self.dateTimeFormatter.string(from: activity.startedAt))"
                                )
                                Spacer()
                                if let endedAt = activity.endedAt {
                                    Text(
                                        "Fin: \(Self.dateTimeFormatter.string(from: endedAt))"
                                    )
                                }
                            }
                            .font(.caption)
                            .foregroundStyle(.secondary)

                            if let replacement = activity.replacement {
                                Divider()
                                DetailTile(
                                    title: "Componente retirado",
                                    value: replacement.removedAssetPath.orFallback(
                                        replacement.removedAssetName.orFallback("No registrado")
                                    )
                                )
                                DetailTile(
                                    title: "Datos del retirado",
                                    value: componentMetadata(
                                        partNumber: replacement.removedPartNumber,
                                        serialNumber: replacement.removedSerialNumber,
                                        model: replacement.removedModel,
                                        manufacturer: replacement.removedManufacturer
                                    )
                                )
                                DetailTile(
                                    title: "Destino",
                                    value: replacement.destinationDescription
                                )
                                DetailTile(
                                    title: "Componente instalado",
                                    value: replacement.installedAssetPath.orFallback(
                                        replacement.installedAssetName.orFallback("No registrado")
                                    )
                                )
                                DetailTile(
                                    title: "Datos del instalado",
                                    value: componentMetadata(
                                        partNumber: replacement.installedPartNumber,
                                        serialNumber: replacement.installedSerialNumber,
                                        model: replacement.installedModel,
                                        manufacturer: replacement.installedManufacturer
                                    )
                                )
                                DetailTile(
                                    title: "Origen",
                                    value: replacement.sourceDescription
                                )
                                DetailTile(title: "Motivo", value: replacement.reason)
                            }
                        }
                        .padding(AppSpacing.md)
                        .background(
                            .background.opacity(0.72),
                            in: RoundedRectangle(cornerRadius: 12, style: .continuous)
                        )
                    }
                }
            }
        }
    }

    private func correctiveValidation(_ report: APICorrectiveReport) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(title: "Pruebas y validación")
                DetailTile(
                    title: "Pruebas funcionales",
                    value: report.functionalTests.orFallback("No registradas")
                )
                DetailTile(
                    title: "Resultado",
                    value: report.validationResult.orFallback("No registrado")
                )
                DetailTile(
                    title: "Liberación para servicio",
                    value: report.serviceReleased ? "Sí" : "No"
                )
                if let releasedAt = report.serviceReleasedAt {
                    DetailTile(
                        title: "Fecha de liberación",
                        value: Self.dateTimeFormatter.string(from: releasedAt)
                    )
                }
                DetailTile(
                    title: "Responsable de validación",
                    value: report.validationResponsible.orFallback("No registrado")
                )
            }
        }
    }

    private func correctiveConclusion(_ report: APICorrectiveReport) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(title: "Resultados finales")
                DetailTile(
                    title: "Estado técnico del equipo",
                    value: report.technicalStatus.orFallback("No registrado")
                )
                DetailTile(
                    title: "Conclusiones",
                    value: report.conclusion.orFallback("No registradas")
                )
                DetailTile(
                    title: "Comentarios adicionales",
                    value: report.additionalComments.orFallback("Sin comentarios")
                )
            }
        }
    }

    private func steps(_ detail: APIReportVersionDetail) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(title: "Pasos del mantenimiento", subtitle: "Pruebas y resultados guardados")
                if let report = detail.preventiveReport, !report.steps.isEmpty {
                    ForEach(report.steps) { step in
                        VStack(alignment: .leading, spacing: AppSpacing.sm) {
                            HStack {
                                Image(systemName: step.isCompleted ? "checkmark.circle.fill" : "circle")
                                    .foregroundStyle(step.isCompleted ? BrandColor.green : .secondary)
                                Text(step.title).font(.headline)
                                Spacer()
                                if let page = step.manualPage {
                                    Text("Pág. \(page)")
                                        .font(.caption)
                                        .foregroundStyle(.secondary)
                                }
                            }
                            if let comment = step.comment, !comment.isEmpty {
                                Text(comment).font(.subheadline).foregroundStyle(.secondary)
                            }
                            ForEach(step.tests) { test in
                                HStack(alignment: .top) {
                                    VStack(alignment: .leading, spacing: 3) {
                                        Text(test.name).font(.subheadline)
                                        if let notes = test.notes, !notes.isEmpty {
                                            Text(notes).font(.caption).foregroundStyle(.secondary)
                                        }
                                    }
                                    Spacer()
                                    Text(test.selectedResult)
                                        .font(.subheadline.weight(.semibold))
                                        .foregroundStyle(BrandColor.red)
                                }
                                .padding(AppSpacing.sm)
                                .background(.background.opacity(0.72), in: RoundedRectangle(cornerRadius: 10, style: .continuous))
                            }
                        }
                        .padding(AppSpacing.md)
                        .background(.background.opacity(0.72), in: RoundedRectangle(cornerRadius: 12, style: .continuous))
                    }
                } else {
                    Text("No hay pasos guardados en esta versión.").foregroundStyle(.secondary)
                }
            }
        }
    }

    private func participants(_ detail: APIReportVersionDetail) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(title: "Participantes y firmas", subtitle: "Firmas capturadas al completar el reporte")
                if detail.participants.isEmpty {
                    Text("No hay participantes guardados.").foregroundStyle(.secondary)
                } else {
                    ForEach(detail.participants) { participant in
                        HStack(alignment: .center, spacing: AppSpacing.md) {
                            VStack(alignment: .leading, spacing: 4) {
                                Text(participant.name).font(.headline)
                                Text(participant.role).font(.caption).foregroundStyle(.secondary)
                            }
                            SignaturePreview(
                                name: participant.name,
                                isSigned: !participant.signatureStrokes.isEmpty,
                                strokes: participant.signatureStrokes.cgPoints
                            )
                        }
                        .padding(AppSpacing.md)
                        .background(.background.opacity(0.72), in: RoundedRectangle(cornerRadius: 12, style: .continuous))
                    }
                }
            }
        }
    }

    @ViewBuilder
    private func evidence(_ detail: APIReportVersionDetail) -> some View {
        if !detail.evidence.isEmpty {
            GlassPanel {
                VStack(alignment: .leading, spacing: AppSpacing.md) {
                    SectionHeaderText(title: "Evidencias", subtitle: "Fotografías asociadas al reporte")
                    StoredReportEvidenceGrid(evidence: detail.evidence)
                }
            }
        }
    }

    private func pdfActions(_ detail: APIReportVersionDetail) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(title: "PDF del reporte", subtitle: "Formato \(detail.generatedReport?.fileName ?? "pendiente de generar")")
                ActionButtonGrid {
                    if detail.generatedReport != nil {
                        Button {
                            Task { await loadPDF() }
                        } label: {
                            Label("Abrir PDF", systemImage: "doc.viewfinder")
                        }
                        .buttonStyle(ActionTileButtonStyle(prominent: true))
                    } else {
                        Button {
                            Task { await generatePDF() }
                        } label: {
                            Label(isGenerating ? "Generando..." : "Generar PDF", systemImage: "doc.badge.plus")
                        }
                        .buttonStyle(ActionTileButtonStyle(prominent: true))
                        .disabled(isGenerating)
                    }
                    /**
                    if let pdfURL {
                        ShareLink(item: pdfURL) {
                            Label("Compartir PDF", systemImage: "square.and.arrow.up")
                        }
                        .buttonStyle(ActionTileButtonStyle())
                    }*/

                    if detail.generatedReport != nil {
                        Button {
                            Task { await prepareEmail(for: detail) }
                        } label: {
                            if isPreparingEmail {
                                HStack(spacing: AppSpacing.sm) {
                                    ProgressView()
                                    Text("Cargando...")
                                }
                            } else {
                                Label("Enviar por correo", systemImage: "envelope.fill")
                            }
                        }
                        .buttonStyle(ActionTileButtonStyle())
                        .disabled(isGenerating || isPreparingEmail)
                    }
                }
            }
        }
    }

    @MainActor
    private func loadDetail() async {
        isLoading = true
        defer { isLoading = false }
        do {
            detail = try await session.withValidAccessToken { token in
                try await reportService.versionDetail(versionID: versionID, accessToken: token)
            }
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    @MainActor
    private func generatePDF() async {
        isGenerating = true
        errorMessage = nil
        defer { isGenerating = false }
        do {
            _ = try await session.withValidAccessToken { token in
                try await reportService.generatePDF(versionID: versionID, accessToken: token)
            }
            await loadDetail()
            await loadPDF()
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    @MainActor
    private func loadPDF() async {
        errorMessage = nil
        do {
            let data = try await session.withValidAccessToken { token in
                try await reportService.downloadPDF(versionID: versionID, accessToken: token)
            }
            let fallbackName = detail?.reportKind == "CORRECTIVE"
                ? "reporte-correctivo.pdf"
                : "reporte-preventivo.pdf"
            let fileName = detail?.generatedReport?.fileName ?? fallbackName
            let url = FileManager.default.temporaryDirectory.appendingPathComponent(fileName)
            try data.write(to: url, options: .atomic)
            pdfData = data
            pdfURL = url
            isPresentingPDF = true
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    @MainActor
    private func prepareEmail(for detail: APIReportVersionDetail) async {
        guard !isPreparingEmail else { return }
        guard MFMailComposeViewController.canSendMail() else {
            errorMessage = "Configura una cuenta en la app Mail del iPad para enviar el reporte."
            return
        }
        guard let recipient = session.currentUser?.email, !recipient.isEmpty else {
            errorMessage = "No se encontró el correo del usuario actual."
            return
        }

        errorMessage = nil
        isPreparingEmail = true
        defer { isPreparingEmail = false }
        do {
            let attachmentData: Data
            if let pdfData {
                attachmentData = pdfData
            } else {
                attachmentData = try await session.withValidAccessToken { token in
                    try await reportService.downloadPDF(versionID: versionID, accessToken: token)
                }
            }
            let fileName = detail.generatedReport?.fileName
                ?? (detail.reportKind == "CORRECTIVE" ? "reporte-correctivo.pdf" : "reporte-preventivo.pdf")
            mailDraft = ReportEmailDraft(
                recipient: recipient,
                subject: emailSubject(for: detail),
                body: emailBody(for: detail),
                attachmentData: attachmentData,
                attachmentFileName: fileName
            )
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    private func emailSubject(for detail: APIReportVersionDetail) -> String {
        let sapCode = detail.activity.sapOrder
            ?? detail.correctiveReport?.sapNotification
            ?? detail.activity.internalCode
        let startedAt = reportStartedAt(for: detail)
        return "\(sapCode) - \(Self.emailDateFormatter.string(from: startedAt)) - \(detail.activity.title)"
    }

    private func emailBody(for detail: APIReportVersionDetail) -> String {
        let startedAt = reportStartedAt(for: detail)
        let endedAt = reportEndedAt(for: detail)
        let equipment = detail.activity.assets.map(\.name).joined(separator: ", ").orFallback("No registrado")
        let sapOrder = detail.activity.sapOrder
            ?? detail.correctiveReport?.sapNotification
            ?? "No registrada"

        return """
        Se adjunta el reporte de mantenimiento finalizado.

        Fecha: \(Self.emailDateFormatter.string(from: startedAt))
        Hora de inicio: \(Self.emailTimeFormatter.string(from: startedAt))
        Hora de fin: \(endedAt.map(Self.emailTimeFormatter.string(from:)) ?? "No registrada")
        Actividad: \(detail.activity.title)
        Equipo a mantener: \(equipment)
        Orden SAP: \(sapOrder)
        """
    }

    private func reportStartedAt(for detail: APIReportVersionDetail) -> Date {
        detail.preventiveReport?.activityStartedAt
            ?? detail.correctiveReport?.correctiveStartedAt
            ?? detail.activity.actualStartAt
            ?? detail.createdAt
    }

    private func reportEndedAt(for detail: APIReportVersionDetail) -> Date? {
        detail.preventiveReport?.activityEndedAt
            ?? detail.correctiveReport?.correctiveEndedAt
            ?? detail.activity.actualEndAt
    }

    private static let dateTimeFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        formatter.locale = Locale(identifier: "es_PE")
        return formatter
    }()

    private static let emailDateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateStyle = .short
        formatter.timeStyle = .none
        formatter.locale = Locale(identifier: "es_PE")
        return formatter
    }()

    private static let emailTimeFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateStyle = .none
        formatter.timeStyle = .short
        formatter.locale = Locale(identifier: "es_PE")
        return formatter
    }()

    private func componentMetadata(
        partNumber: String?,
        serialNumber: String?,
        model: String?,
        manufacturer: String?
    ) -> String {
        [
            "PN: \(partNumber.orFallback("S/D"))",
            "SN: \(serialNumber.orFallback("S/D"))",
            "Modelo: \(model.orFallback("S/D"))",
            "Fabricante: \(manufacturer.orFallback("S/D"))"
        ].joined(separator: " · ")
    }
}

struct PDFDocumentViewer: View {
    @Environment(\.dismiss) private var dismiss
    let data: Data

    var body: some View {
        NavigationStack {
            PDFKitView(data: data)
                .navigationTitle("PDF del reporte")
                .navigationBarTitleDisplayMode(.inline)
                .toolbar {
                    ToolbarItem(placement: .confirmationAction) {
                        Button("Cerrar") { dismiss() }
                    }
                }
        }
    }
}

private struct ReportEmailDraft: Identifiable {
    let id = UUID()
    let recipient: String
    let subject: String
    let body: String
    let attachmentData: Data
    let attachmentFileName: String
}

private struct ReportMailComposer: UIViewControllerRepresentable {
    @Environment(\.dismiss) private var dismiss
    let draft: ReportEmailDraft
    let onCompletion: (Result<MFMailComposeResult, Error>) -> Void

    func makeCoordinator() -> Coordinator {
        Coordinator(parent: self)
    }

    func makeUIViewController(context: Context) -> MFMailComposeViewController {
        let composer = MFMailComposeViewController()
        composer.mailComposeDelegate = context.coordinator
        composer.setToRecipients([draft.recipient])
        composer.setSubject(draft.subject)
        composer.setMessageBody(draft.body, isHTML: false)
        composer.addAttachmentData(
            draft.attachmentData,
            mimeType: "application/pdf",
            fileName: draft.attachmentFileName
        )
        return composer
    }

    func updateUIViewController(
        _ uiViewController: MFMailComposeViewController,
        context: Context
    ) {}

    final class Coordinator: NSObject, MFMailComposeViewControllerDelegate {
        private let parent: ReportMailComposer

        init(parent: ReportMailComposer) {
            self.parent = parent
        }

        func mailComposeController(
            _ controller: MFMailComposeViewController,
            didFinishWith result: MFMailComposeResult,
            error: Error?
        ) {
            if let error {
                parent.onCompletion(.failure(error))
            } else {
                parent.onCompletion(.success(result))
            }
            parent.dismiss()
        }
    }
}

private struct PDFKitView: UIViewRepresentable {
    let data: Data

    func makeUIView(context: Context) -> PDFView {
        let view = PDFView()
        view.autoScales = true
        view.displayMode = .singlePageContinuous
        view.displayDirection = .vertical
        view.document = PDFDocument(data: data)
        return view
    }

    func updateUIView(_ view: PDFView, context: Context) {
        view.document = PDFDocument(data: data)
    }
}

private extension Optional where Wrapped == String {
    func orFallback(_ fallback: String) -> String {
        guard let value = self, !value.isEmpty else { return fallback }
        return value
    }
}

private extension String {
    func orFallback(_ fallback: String) -> String {
        isEmpty ? fallback : self
    }
}

private extension Array where Element == [APISignaturePoint] {
    var cgPoints: [[CGPoint]] { map(\.cgPoints) }
}
