import PDFKit
import SwiftUI

/// Read-only version view. The PDF is generated by the backend and opened locally with PDFKit.
struct PDFPreviewView: View {
    @EnvironmentObject private var session: SessionStore
    let versionID: String

    @State private var detail: APIReportVersionDetail?
    @State private var pdfData: Data?
    @State private var pdfURL: URL?
    @State private var isLoading = true
    @State private var isGenerating = false
    @State private var isPresentingPDF = false
    @State private var errorMessage: String?

    private var reportService: ReportAPIService {
        ReportAPIService(
            baseURLString: UserDefaults.standard.string(forKey: "apiBaseURL") ?? ""
        )
    }

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: AppSpacing.xl) {
                if let detail {
                    header(detail)
                    generalData(detail)
                    if detail.reportKind == "CORRECTIVE" {
                        correctiveContent(detail)
                    } else if detail.reportKind == "CALIBRATION" {
                        calibrationContent(detail)
                    } else {
                        steps(detail)
                    }
                    participants(detail)
                    evidence(detail)
                    if detail.documentStatus == "FINALIZED" {
                        pdfActions(detail)
                    }
                } else if isLoading {
                    ProgressView("Cargando versión del reporte")
                        .frame(maxWidth: .infinity, minHeight: 260)
                }

                if let errorMessage {
                    Text(errorMessage)
                        .foregroundStyle(.red)
                        .frame(maxWidth: .infinity, alignment: .leading)
                }
            }
            .padding(AppSpacing.lg)
            .frame(maxWidth: 900, alignment: .leading)
            .frame(maxWidth: .infinity)
        }
        .background(MaintenanceScreenBackground())
        .navigationTitle("Versión del reporte")
        .task { await loadDetail() }
        .sheet(isPresented: $isPresentingPDF) {
            if let pdfData {
                PDFDocumentViewer(data: pdfData)
            }
        }
    }

    private func header(_ detail: APIReportVersionDetail) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                Text(detail.activity.internalCode)
                    .font(.caption.weight(.bold))
                    .foregroundStyle(BrandColor.red)
                Text(detail.activity.title)
                    .font(.system(.largeTitle, design: .rounded).weight(.black))
                HStack(spacing: AppSpacing.sm) {
                    Text("Versión \(detail.versionNumber)")
                    Text(detail.documentStatus)
                        .font(.caption.weight(.bold))
                        .foregroundStyle(BrandColor.green)
                }
                if let summary = detail.summary, !summary.isEmpty {
                    Text(summary)
                        .foregroundStyle(.secondary)
                }
                Text("Lectura histórica: estos datos pertenecen a esta versión y no se editan desde aquí.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
        }
    }

    private func generalData(_ detail: APIReportVersionDetail) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(title: "Datos generales", subtitle: "Información guardada en el reporte")
                DetailTile(title: "Sede", value: detail.activity.site.orFallback("No registrada"))
                DetailTile(title: "Proyecto", value: detail.activity.project.orFallback("No registrado"))
                DetailTile(title: "Etapa", value: detail.activity.stage.orFallback("No registrada"))
                DetailTile(title: "Sistema", value: detail.activity.system.orFallback("No registrado"))
                DetailTile(title: "Subsistema", value: detail.activity.subsystem)
                DetailTile(title: "Equipos", value: detail.activity.assets.map(\.name).joined(separator: ", ").orFallback("No registrados"))
                DetailTile(title: "Ubicación física", value: detail.activity.locationPath.orFallback("No registrada"))
                if let report = detail.preventiveReport {
                    DetailTile(title: "Fecha de actividad", value: report.actualDate)
                    DetailTile(title: "Inicio de actividad", value: Self.dateTimeFormatter.string(from: report.activityStartedAt))
                    if let endedAt = report.activityEndedAt {
                        DetailTile(title: "Fin de actividad", value: Self.dateTimeFormatter.string(from: endedAt))
                    }
                    DetailTile(title: "Estado final del equipo", value: report.finalResult.orFallback("No registrado"))
                    DetailTile(title: "Comentarios adicionales", value: report.additionalComments.orFallback("Sin comentarios"))
                }
            }
        }
    }

    @ViewBuilder
    private func correctiveContent(_ detail: APIReportVersionDetail) -> some View {
        if let report = detail.correctiveReport {
            correctiveFailure(report)
            correctiveActivities(report)
            correctiveValidation(report)
            correctiveConclusion(report)
        }
    }

    @ViewBuilder
    private func calibrationContent(
        _ detail: APIReportVersionDetail
    ) -> some View {
        if let report = detail.calibrationReport {
            GlassPanel {
                VStack(alignment: .leading, spacing: AppSpacing.md) {
                    SectionHeaderText(
                        title: "Calibración del circuito de vía",
                        subtitle: "Mediciones guardadas en esta versión"
                    )
                    DetailTile(
                        title: "Circuito de vía",
                        value: report.trackCircuitName
                    )
                    DetailTile(
                        title: "Ubicación",
                        value: report.location
                    )
                    DetailTile(
                        title: "Fecha de calibración",
                        value: report.calibrationDate
                    )
                    DetailTile(
                        title: "Frecuencia",
                        value: "\(report.frequency.orFallback("-")) Hz"
                    )
                    DetailTile(
                        title: "Jumpers del transmisor",
                        value: report.transmitterJumpers.orFallback("-")
                    )

                    ForEach(report.receivers) { receiver in
                        VStack(alignment: .leading, spacing: AppSpacing.sm) {
                            Label(
                                "Receptor \(receiver.sequence)",
                                systemImage: "dot.radiowaves.left.and.right"
                            )
                            .font(.headline)
                            .foregroundStyle(BrandColor.red)
                            DetailTile(
                                title: "Jumpers",
                                value: receiver.jumpers.orFallback("-")
                            )
                            DetailTile(
                                title: "TCA9",
                                value: receiver.tca9.orFallback("-")
                            )
                            DetailTile(
                                title: "Corriente de riel",
                                value: "\(receiver.railCurrent.orFallback("-")) mA"
                            )
                        }
                        .padding(AppSpacing.md)
                        .background(
                            .background.opacity(0.72),
                            in: RoundedRectangle(cornerRadius: 12)
                        )
                    }
                }
            }
        }
    }

    private func correctiveFailure(_ report: APICorrectiveReport) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(
                    title: "Datos del evento y falla",
                    subtitle: "Información guardada en esta versión"
                )
                DetailTile(title: "Evento", value: report.eventCode.orFallback("No registrado"))
                DetailTile(
                    title: "Nombre del evento SAP",
                    value: report.sapEventName.orFallback("No registrado")
                )
                DetailTile(
                    title: "Notificación SAP",
                    value: report.sapNotification.orFallback("No registrada")
                )
                DetailTile(
                    title: "Asset afectado",
                    value: report.affectedAssetPath.orFallback("No registrado")
                )
                DetailTile(
                    title: "Síntoma registrado",
                    value: report.symptom.orFallback("No registrado")
                )
                DetailTile(
                    title: "Descripción técnica",
                    value: report.technicalDescription.orFallback("No registrada")
                )
                DetailTile(
                    title: "Impacto operacional",
                    value: report.operationalImpact.orFallback("No registrado")
                )
                DetailTile(
                    title: "Análisis de la falla",
                    value: report.failureAnalysisType.orFallback("No registrado")
                )
            }
        }
    }

    private func correctiveActivities(_ report: APICorrectiveReport) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(
                    title: "Actividades realizadas",
                    subtitle: "Intervenciones y cambios de componentes"
                )
                if report.activities.isEmpty {
                    Text("No hay actividades registradas.").foregroundStyle(.secondary)
                } else {
                    ForEach(report.activities) { activity in
                        VStack(alignment: .leading, spacing: AppSpacing.sm) {
                            Label(
                                activity.name,
                                systemImage: activity.replacement == nil
                                    ? "wrench.and.screwdriver"
                                    : "arrow.triangle.2.circlepath"
                            )
                            .font(.headline)

                            if !activity.description.isEmpty {
                                Text(activity.description)
                            }

                            HStack {
                                Text(
                                    "Inicio: \(Self.dateTimeFormatter.string(from: activity.startedAt))"
                                )
                                Spacer()
                                if let endedAt = activity.endedAt {
                                    Text(
                                        "Fin: \(Self.dateTimeFormatter.string(from: endedAt))"
                                    )
                                }
                            }
                            .font(.caption)
                            .foregroundStyle(.secondary)

                            if let replacement = activity.replacement {
                                Divider()
                                DetailTile(
                                    title: "Componente retirado",
                                    value: replacement.removedAssetPath.orFallback(
                                        replacement.removedAssetName.orFallback("No registrado")
                                    )
                                )
                                DetailTile(
                                    title: "Datos del retirado",
                                    value: componentMetadata(
                                        partNumber: replacement.removedPartNumber,
                                        serialNumber: replacement.removedSerialNumber,
                                        model: replacement.removedModel,
                                        manufacturer: replacement.removedManufacturer
                                    )
                                )
                                DetailTile(
                                    title: "Destino",
                                    value: replacement.destinationDescription
                                )
                                DetailTile(
                                    title: "Componente instalado",
                                    value: replacement.installedAssetPath.orFallback(
                                        replacement.installedAssetName.orFallback("No registrado")
                                    )
                                )
                                DetailTile(
                                    title: "Datos del instalado",
                                    value: componentMetadata(
                                        partNumber: replacement.installedPartNumber,
                                        serialNumber: replacement.installedSerialNumber,
                                        model: replacement.installedModel,
                                        manufacturer: replacement.installedManufacturer
                                    )
                                )
                                DetailTile(
                                    title: "Origen",
                                    value: replacement.sourceDescription
                                )
                                DetailTile(title: "Motivo", value: replacement.reason)
                            }
                        }
                        .padding(AppSpacing.md)
                        .background(
                            .background.opacity(0.72),
                            in: RoundedRectangle(cornerRadius: 12, style: .continuous)
                        )
                    }
                }
            }
        }
    }

    private func correctiveValidation(_ report: APICorrectiveReport) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(title: "Pruebas y validación")
                DetailTile(
                    title: "Pruebas funcionales",
                    value: report.functionalTests.orFallback("No registradas")
                )
                DetailTile(
                    title: "Resultado",
                    value: report.validationResult.orFallback("No registrado")
                )
                DetailTile(
                    title: "Liberación para servicio",
                    value: report.serviceReleased ? "Sí" : "No"
                )
                if let releasedAt = report.serviceReleasedAt {
                    DetailTile(
                        title: "Fecha de liberación",
                        value: Self.dateTimeFormatter.string(from: releasedAt)
                    )
                }
                DetailTile(
                    title: "Responsable de validación",
                    value: report.validationResponsible.orFallback("No registrado")
                )
            }
        }
    }

    private func correctiveConclusion(_ report: APICorrectiveReport) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(title: "Resultados finales")
                DetailTile(
                    title: "Estado técnico del equipo",
                    value: report.technicalStatus.orFallback("No registrado")
                )
                DetailTile(
                    title: "Conclusiones",
                    value: report.conclusion.orFallback("No registradas")
                )
                DetailTile(
                    title: "Comentarios adicionales",
                    value: report.additionalComments.orFallback("Sin comentarios")
                )
            }
        }
    }

    private func steps(_ detail: APIReportVersionDetail) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(title: "Pasos del mantenimiento", subtitle: "Pruebas y resultados guardados")
                if let report = detail.preventiveReport, !report.steps.isEmpty {
                    ForEach(report.steps) { step in
                        VStack(alignment: .leading, spacing: AppSpacing.sm) {
                            HStack {
                                Image(systemName: step.isCompleted ? "checkmark.circle.fill" : "circle")
                                    .foregroundStyle(step.isCompleted ? BrandColor.green : .secondary)
                                Text(step.title).font(.headline)
                                Spacer()
                                if let page = step.manualPage {
                                    Text("Pág. \(page)")
                                        .font(.caption)
                                        .foregroundStyle(.secondary)
                                }
                            }
                            if let comment = step.comment, !comment.isEmpty {
                                Text(comment).font(.subheadline).foregroundStyle(.secondary)
                            }
                            ForEach(step.tests) { test in
                                HStack(alignment: .top) {
                                    VStack(alignment: .leading, spacing: 3) {
                                        Text(test.name).font(.subheadline)
                                        if let notes = test.notes, !notes.isEmpty {
                                            Text(notes).font(.caption).foregroundStyle(.secondary)
                                        }
                                    }
                                    Spacer()
                                    Text(test.selectedResult)
                                        .font(.subheadline.weight(.semibold))
                                        .foregroundStyle(BrandColor.red)
                                }
                                .padding(AppSpacing.sm)
                                .background(.background.opacity(0.72), in: RoundedRectangle(cornerRadius: 10, style: .continuous))
                            }
                        }
                        .padding(AppSpacing.md)
                        .background(.background.opacity(0.72), in: RoundedRectangle(cornerRadius: 12, style: .continuous))
                    }
                } else {
                    Text("No hay pasos guardados en esta versión.").foregroundStyle(.secondary)
                }
            }
        }
    }

    private func participants(_ detail: APIReportVersionDetail) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(title: "Participantes y firmas", subtitle: "Firmas capturadas al completar el reporte")
                if detail.participants.isEmpty {
                    Text("No hay participantes guardados.").foregroundStyle(.secondary)
                } else {
                    ForEach(detail.participants) { participant in
                        HStack(alignment: .center, spacing: AppSpacing.md) {
                            VStack(alignment: .leading, spacing: 4) {
                                Text(participant.name).font(.headline)
                                Text(participant.role).font(.caption).foregroundStyle(.secondary)
                            }
                            SignaturePreview(
                                name: participant.name,
                                isSigned: !participant.signatureStrokes.isEmpty,
                                strokes: participant.signatureStrokes.cgPoints
                            )
                        }
                        .padding(AppSpacing.md)
                        .background(.background.opacity(0.72), in: RoundedRectangle(cornerRadius: 12, style: .continuous))
                    }
                }
            }
        }
    }

    @ViewBuilder
    private func evidence(_ detail: APIReportVersionDetail) -> some View {
        if !detail.evidence.isEmpty {
            GlassPanel {
                VStack(alignment: .leading, spacing: AppSpacing.md) {
                    SectionHeaderText(title: "Evidencias", subtitle: "Fotografías asociadas al reporte")
                    StoredReportEvidenceGrid(evidence: detail.evidence)
                }
            }
        }
    }

    private func pdfActions(_ detail: APIReportVersionDetail) -> some View {
        GlassPanel {
            VStack(alignment: .leading, spacing: AppSpacing.md) {
                SectionHeaderText(title: "PDF del reporte", subtitle: "Formato \(detail.generatedReport?.fileName ?? "pendiente de generar")")
                ActionButtonGrid {
                    if detail.generatedReport != nil {
                        Button {
                            Task { await loadPDF() }
                        } label: {
                            Label("Abrir PDF", systemImage: "doc.viewfinder")
                        }
                        .buttonStyle(ActionTileButtonStyle(prominent: true))
                    } else {
                        Button {
                            Task { await generatePDF() }
                        } label: {
                            Label(isGenerating ? "Generando..." : "Generar PDF", systemImage: "doc.badge.plus")
                        }
                        .buttonStyle(ActionTileButtonStyle(prominent: true))
                        .disabled(isGenerating)
                    }

                    if let pdfURL {
                        ShareLink(item: pdfURL) {
                            Label("Compartir PDF", systemImage: "square.and.arrow.up")
                        }
                        .buttonStyle(ActionTileButtonStyle())
                    }
                }
            }
        }
    }

    @MainActor
    private func loadDetail() async {
        isLoading = true
        defer { isLoading = false }
        do {
            detail = try await session.withValidAccessToken { token in
                try await reportService.versionDetail(versionID: versionID, accessToken: token)
            }
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    @MainActor
    private func generatePDF() async {
        isGenerating = true
        errorMessage = nil
        defer { isGenerating = false }
        do {
            _ = try await session.withValidAccessToken { token in
                try await reportService.generatePDF(versionID: versionID, accessToken: token)
            }
            await loadDetail()
            await loadPDF()
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    @MainActor
    private func loadPDF() async {
        errorMessage = nil
        do {
            let data = try await session.withValidAccessToken { token in
                try await reportService.downloadPDF(versionID: versionID, accessToken: token)
            }
            let fallbackName = detail?.reportKind == "CORRECTIVE"
                ? "reporte-correctivo.pdf"
                : "reporte-preventivo.pdf"
            let fileName = detail?.generatedReport?.fileName ?? fallbackName
            let url = FileManager.default.temporaryDirectory.appendingPathComponent(fileName)
            try data.write(to: url, options: .atomic)
            pdfData = data
            pdfURL = url
            isPresentingPDF = true
        } catch {
            errorMessage = error.localizedDescription
        }
    }

    private static let dateTimeFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        formatter.locale = Locale(identifier: "es_PE")
        return formatter
    }()

    private func componentMetadata(
        partNumber: String?,
        serialNumber: String?,
        model: String?,
        manufacturer: String?
    ) -> String {
        [
            "PN: \(partNumber.orFallback("S/D"))",
            "SN: \(serialNumber.orFallback("S/D"))",
            "Modelo: \(model.orFallback("S/D"))",
            "Fabricante: \(manufacturer.orFallback("S/D"))"
        ].joined(separator: " · ")
    }
}

struct PDFDocumentViewer: View {
    @Environment(\.dismiss) private var dismiss
    let data: Data

    var body: some View {
        NavigationStack {
            PDFKitView(data: data)
                .navigationTitle("PDF del reporte")
                .navigationBarTitleDisplayMode(.inline)
                .toolbar {
                    ToolbarItem(placement: .confirmationAction) {
                        Button("Cerrar") { dismiss() }
                    }
                }
        }
    }
}

private struct PDFKitView: UIViewRepresentable {
    let data: Data

    func makeUIView(context: Context) -> PDFView {
        let view = PDFView()
        view.autoScales = true
        view.displayMode = .singlePageContinuous
        view.displayDirection = .vertical
        view.document = PDFDocument(data: data)
        return view
    }

    func updateUIView(_ view: PDFView, context: Context) {
        view.document = PDFDocument(data: data)
    }
}

private extension Optional where Wrapped == String {
    func orFallback(_ fallback: String) -> String {
        guard let value = self, !value.isEmpty else { return fallback }
        return value
    }
}

private extension String {
    func orFallback(_ fallback: String) -> String {
        isEmpty ? fallback : self
    }
}

private extension Array where Element == [APISignaturePoint] {
    var cgPoints: [[CGPoint]] { map(\.cgPoints) }
}
